// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\crud\ControllerImpl.java.vsl) on 05/13/2012 07:38:36-0300
package com.wim.reportviewer.domain.crud;

import java.io.Serializable;

/**
 * @see com.wim.reportviewer.domain.crud.SampleClassController
 */
public class SampleClassControllerImpl
    extends SampleClassController
    implements Serializable
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 3399316226615338220L;
}