// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl) on 05/11/2012 10:26:51-0300
package com.wim.reportviewer.web.report.loadImage;

import java.io.IOException;
import java.util.Map;

import javax.servlet.ServletOutputStream;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.wim.reportviewer.web.WebAppUtil;
import com.wim.reportviewer.web.report.ReportConstants;

/**
 * @see com.wim.reportviewer.web.report.loadImage.LoadImageReportController
 */
public class LoadImageReportControllerImpl
    extends LoadImageReportController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -5583232284104362294L;

    /**
     * @see com.wim.reportviewer.web.report.loadImage.LoadImageReportController#fillResponseWithImage()
     */
    @Override
    public void fillResponseWithImage()
    {
        @SuppressWarnings("rawtypes")
        final Map imagesMap = (Map)WebAppUtil.getSession().getAttribute(ReportConstants.IMAGES_MAP);
        final HttpServletRequest request=WebAppUtil.getRequest();
        final HttpServletResponse response=WebAppUtil.getResponse();
    
        String imageName = request.getParameter("image");
        byte[] imageData = (byte[]) imagesMap.get(imageName);
        response.setContentLength(imageData.length);
    
        String type = "image/gif";
        if(imageName.endsWith(".png"))
            type="image/png";
        else if(imageName.endsWith(".jpg") || imageName.endsWith(".jpeg"))
            type="image/jpeg";
    
        response.setContentType(type);
    
        try {
            ServletOutputStream ouputStream = response.getOutputStream();
            ouputStream.write(imageData, 0, imageData.length);
            ouputStream.flush();
            ouputStream.close();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    
        WebAppUtil.getFacesContext().responseComplete();
    }
}